### PR TITLE
Add Kubernetes Plugin

### PR DESCRIPTION
**Pull request by Davincible**
Allows you to run the cli inside a Kubernetes environment and use the `kubernetes` registry.

### CODE REVIEW

**Comment by asim** [comment]
@xpunch

**Comment by xpunch** [comment]
Can you replace it with github.com/go-micro/plugins/v4/registry/kubernetes?

**Comment by Davincible** [comment]
Done.

As a general question, I'm a bit confused between the code duplication between the community repo and asim/go-micro repo, since plugins etc are present in both. Which one should be used now?

**Review by xpunch — APPROVED** [review]

**Comment by xpunch** [comment]
> Done.
> 
> As a general question, I'm a bit confused between the code duplication between the community repo and asim/go-micro repo, since plugins etc are present in both. Which one should be used now?

https://github.com/asim/go-micro/discussions/2473

**Comment by asim** [comment]
@xpunch you're now the sole admin of the org so you can add @Davincible and others as maintainers however you like. Might make life easier.

**Comment by xpunch** [comment]
@Davincible I've invited you as the maintainer, you can accept it if you want.

**Pull request merged**
